#!/usr/bin/env node
/**
 * RecoverAI canonical endpoint test runner.
 * Uses test/.testdata.json generated by seed.js and runs one reusable test suite.
 */

const http = require('http');
const fs = require('fs');
const path = require('path');

const DATA_FILE = path.join(__dirname, '.testdata.json');
const VERBOSE = process.argv.includes('--verbose');
const PORT_ARG = process.argv.find((arg, idx) => process.argv[idx - 1] === '--port');

if (!fs.existsSync(DATA_FILE)) {
  console.error('[test] Missing test/.testdata.json. Run: node -r dotenv/config test/seed.js');
  process.exit(1);
}

const TD = JSON.parse(fs.readFileSync(DATA_FILE, 'utf-8'));
const PORT = parseInt(PORT_ARG || TD.port || '3000', 10);

function req(method, route, body, cookie, headers = {}) {
  return new Promise((resolve, reject) => {
    const payload = body ? JSON.stringify(body) : '';
    const request = http.request(
      {
        hostname: 'localhost',
        port: PORT,
        path: route,
        method,
        headers: {
          'Content-Type': 'application/json',
          ...(cookie ? { Cookie: cookie } : {}),
          ...(payload ? { 'Content-Length': Buffer.byteLength(payload) } : {}),
          ...headers,
        },
      },
      (response) => {
        let raw = '';
        response.on('data', (chunk) => { raw += chunk; });
        response.on('end', () => {
          let json = null;
          try {
            json = raw ? JSON.parse(raw) : null;
          } catch {
            json = null;
          }
          resolve({
            status: response.statusCode,
            headers: response.headers,
            raw,
            json,
          });
        });
      }
    );

    request.on('error', reject);
    if (payload) request.write(payload);
    request.end();
  });
}

function extractCookie(headers) {
  const setCookie = headers['set-cookie'];
  if (!Array.isArray(setCookie) || setCookie.length === 0) return '';
  return setCookie.map((cookie) => cookie.split(';')[0]).join('; ');
}

const results = [];
let passCount = 0;
let failCount = 0;

function curl(method, route, body, useCookie, extraHeaders = {}) {
  let cmd = `curl -s -X ${method} "http://localhost:${PORT}${route}"`;
  cmd += ' -H "Content-Type: application/json"';
  if (useCookie) cmd += ' -b cookies.txt';
  for (const [k, v] of Object.entries(extraHeaders)) {
    cmd += ` -H "${k}: ${v}"`;
  }
  if (body) cmd += ` -d '${JSON.stringify(body)}'`;
  return cmd;
}

function record(name, ok, actual, expected, curlCmd) {
  results.push({ name, ok, actual, expected, curl: curlCmd });
  if (ok) {
    passCount += 1;
    console.log(`  PASS ${name}`);
  } else {
    failCount += 1;
    console.log(`  FAIL ${name}`);
    console.log(`    expected: ${JSON.stringify(expected)}`);
    console.log(`    actual:   ${JSON.stringify(actual)}`);
  }

  if (VERBOSE && actual) {
    const printable = typeof actual === 'string' ? actual : JSON.stringify(actual);
    console.log(`    response: ${printable.slice(0, 600)}`);
  }
}

function endSummary() {
  console.log('\n---------------------------------------------------');
  console.log(`Total: ${passCount + failCount} | Pass: ${passCount} | Fail: ${failCount}`);
  console.log('---------------------------------------------------\n');
}

async function run() {
  console.log(`\nRecoverAI Full Test Suite (port ${PORT})`);
  console.log(`Using data file: ${DATA_FILE}\n`);

  // Baseline login + cookie refresh.
  const login = await req('POST', '/api/auth/login', { email: TD.email, password: TD.password });
  const freshCookie = extractCookie(login.headers);
  const fallbackCookie = typeof TD.cookie === 'string' ? TD.cookie : '';
  const cookie = freshCookie || fallbackCookie;
  record(
    'POST /api/auth/login -> 200 (or 429 with cached cookie)',
    (login.status === 200 && !!freshCookie) || (login.status === 429 && !!fallbackCookie),
    { status: login.status, hasFreshCookie: !!freshCookie, usedFallbackCookie: !freshCookie && !!fallbackCookie },
    { status: '200_or_429_with_cookie' },
    curl('POST', '/api/auth/login', { email: TD.email, password: TD.password }, false)
  );

  if (!cookie) {
    console.error('\nCannot continue tests without auth cookie.');
    process.exit(1);
  }

  TD.cookie = cookie;
  fs.writeFileSync(DATA_FILE, JSON.stringify(TD, null, 2));

  console.log('\n[Health + platform]');
  const health = await req('GET', '/health');
  record(
    'GET /health -> 200 + status ok',
    health.status === 200 && health.json?.status === 'ok',
    { status: health.status, statusField: health.json?.status },
    { status: 200, statusField: 'ok' },
    curl('GET', '/health', null, false)
  );

  const notFound = await req('GET', '/api/unknown-endpoint');
  record(
    'GET /api/unknown-endpoint -> 404',
    notFound.status === 404,
    { status: notFound.status },
    { status: 404 },
    curl('GET', '/api/unknown-endpoint', null, false)
  );

  console.log('\n[Auth]');
  const signupMissing = await req('POST', '/api/auth/signup', { email: 'x@x.com' });
  record(
    'POST /api/auth/signup missing fields -> 400',
    signupMissing.status === 400,
    { status: signupMissing.status, error: signupMissing.json?.error },
    { status: 400 },
    curl('POST', '/api/auth/signup', { email: 'x@x.com' }, false)
  );

  const signupConflict = await req('POST', '/api/auth/signup', {
    companyName: TD.companyName,
    email: TD.email,
    password: TD.password,
  });
  record(
    'POST /api/auth/signup existing email -> 409',
    signupConflict.status === 409,
    { status: signupConflict.status, error: signupConflict.json?.error },
    { status: 409 },
    curl(
      'POST',
      '/api/auth/signup',
      { companyName: TD.companyName, email: TD.email, password: TD.password },
      false
    )
  );

  const badLogin = await req('POST', '/api/auth/login', { email: TD.email, password: 'WrongPass123!' });
  record(
    'POST /api/auth/login wrong password -> 401/429',
    badLogin.status === 401 || badLogin.status === 429,
    { status: badLogin.status },
    { status: '401_or_429' },
    curl('POST', '/api/auth/login', { email: TD.email, password: 'WrongPass123!' }, false)
  );

  const meAuth = await req('GET', '/api/auth/me', null, cookie);
  record(
    'GET /api/auth/me with auth -> 200',
    meAuth.status === 200 && meAuth.json?.user?.email === TD.email,
    { status: meAuth.status, email: meAuth.json?.user?.email },
    { status: 200, email: TD.email },
    curl('GET', '/api/auth/me', null, true)
  );

  const meNoAuth = await req('GET', '/api/auth/me');
  record(
    'GET /api/auth/me no auth -> 401',
    meNoAuth.status === 401,
    { status: meNoAuth.status },
    { status: 401 },
    curl('GET', '/api/auth/me', null, false)
  );

  const refreshOk = await req('POST', '/api/auth/refresh', null, cookie);
  record(
    'POST /api/auth/refresh with token -> 200',
    refreshOk.status === 200,
    { status: refreshOk.status },
    { status: 200 },
    curl('POST', '/api/auth/refresh', null, true)
  );

  const refreshNoToken = await req('POST', '/api/auth/refresh');
  record(
    'POST /api/auth/refresh no token -> 401',
    refreshNoToken.status === 401,
    { status: refreshNoToken.status },
    { status: 401 },
    curl('POST', '/api/auth/refresh', null, false)
  );

  const logoutOk = await req('POST', '/api/auth/logout', null, cookie);
  record(
    'POST /api/auth/logout -> 200',
    logoutOk.status === 200,
    { status: logoutOk.status },
    { status: 200 },
    curl('POST', '/api/auth/logout', null, true)
  );

  const sessionsList = await req('GET', '/api/auth/sessions', null, cookie);
  record(
    'GET /api/auth/sessions -> 200',
    sessionsList.status === 200 && Array.isArray(sessionsList.json?.data),
    { status: sessionsList.status, total: sessionsList.json?.data?.length },
    { status: 200, data: 'array' },
    curl('GET', '/api/auth/sessions', null, true)
  );

  const oauthNoCode = await req('POST', '/api/auth/oauth/google/callback', {});
  record(
    'POST /api/auth/oauth/google/callback no code -> 400',
    oauthNoCode.status === 400,
    { status: oauthNoCode.status },
    { status: 400 },
    curl('POST', '/api/auth/oauth/google/callback', {}, false)
  );

  console.log('\n[Stripe]');
  const connectNoAuth = await req('POST', '/api/stripe/connect', { stripeApiKey: 'sk_test_fake' });
  record(
    'POST /api/stripe/connect no auth -> 401',
    connectNoAuth.status === 401,
    { status: connectNoAuth.status },
    { status: 401 },
    curl('POST', '/api/stripe/connect', { stripeApiKey: 'sk_test_fake' }, false)
  );

  const connectMissingKey = await req('POST', '/api/stripe/connect', {}, cookie);
  record(
    'POST /api/stripe/connect missing key -> 400',
    connectMissingKey.status === 400,
    { status: connectMissingKey.status },
    { status: 400 },
    curl('POST', '/api/stripe/connect', {}, true)
  );

  const connectInvalidKey = await req('POST', '/api/stripe/connect', { stripeApiKey: 'sk_test_invalid_key' }, cookie);
  record(
    'POST /api/stripe/connect invalid key -> 400',
    connectInvalidKey.status === 400,
    { status: connectInvalidKey.status, error: connectInvalidKey.json?.error },
    { status: 400 },
    curl('POST', '/api/stripe/connect', { stripeApiKey: 'sk_test_invalid_key' }, true)
  );

  const syncNoAuth = await req('POST', '/api/stripe/sync');
  record(
    'POST /api/stripe/sync no auth -> 401',
    syncNoAuth.status === 401,
    { status: syncNoAuth.status },
    { status: 401 },
    curl('POST', '/api/stripe/sync', null, false)
  );

  const syncNoConnection = await req('POST', '/api/stripe/sync', null, cookie);
  record(
    'POST /api/stripe/sync when not connected -> 400',
    syncNoConnection.status === 400,
    { status: syncNoConnection.status, error: syncNoConnection.json?.error },
    { status: 400 },
    curl('POST', '/api/stripe/sync', null, true)
  );

  const webhookInvalid = await req(
    'POST',
    '/api/stripe/webhook',
    { type: 'invoice.payment_failed' },
    null,
    { 'stripe-signature': 'fake_signature' }
  );
  record(
    'POST /api/stripe/webhook invalid signature -> 400',
    webhookInvalid.status === 400,
    { status: webhookInvalid.status },
    { status: 400 },
    curl(
      'POST',
      '/api/stripe/webhook',
      { type: 'invoice.payment_failed' },
      false,
      { 'stripe-signature': 'fake_signature' }
    )
  );

  const invoicesList = await req('GET', '/api/stripe/invoices?page=1&limit=10', null, cookie);
  record(
    'GET /api/stripe/invoices -> 200',
    invoicesList.status === 200 && typeof invoicesList.json?.total === 'number',
    { status: invoicesList.status, total: invoicesList.json?.total },
    { status: 200, total: 'number' },
    curl('GET', '/api/stripe/invoices?page=1&limit=10', null, true)
  );

  const firstInvoiceId = TD.invoices?.[0]?.id;
  if (firstInvoiceId) {
    const invoiceById = await req('GET', `/api/stripe/invoices/${firstInvoiceId}`, null, cookie);
    const returnedInvoiceId = invoiceById.json?.id || invoiceById.json?.data?.id;
    record(
      'GET /api/stripe/invoices/:id existing -> 200',
      invoiceById.status === 200 && returnedInvoiceId === firstInvoiceId,
      { status: invoiceById.status, id: returnedInvoiceId },
      { status: 200, id: firstInvoiceId },
      curl('GET', `/api/stripe/invoices/${firstInvoiceId}`, null, true)
    );
  }

  const invoiceMissing = await req('GET', '/api/stripe/invoices/00000000-0000-0000-0000-000000000000', null, cookie);
  record(
    'GET /api/stripe/invoices/:id missing -> 404',
    invoiceMissing.status === 404,
    { status: invoiceMissing.status },
    { status: 404 },
    curl('GET', '/api/stripe/invoices/00000000-0000-0000-0000-000000000000', null, true)
  );

  console.log('\n[Tenant isolation]');
  if (firstInvoiceId) {
    const intruderEmail = `recoverai_intruder_${Date.now()}@example.com`;
    const intruderPassword = 'IntruderPass1!';
    const intruderSignup = await req('POST', '/api/auth/signup', {
      companyName: 'RecoverAI Intruder Co',
      email: intruderEmail,
      password: intruderPassword,
    });
    const intruderCookie = extractCookie(intruderSignup.headers);
    const crossTenantRead = await req('GET', `/api/invoices/${firstInvoiceId}`, null, intruderCookie);
    record(
      'Cross-tenant invoice read is blocked -> 401/404',
      crossTenantRead.status === 401 || crossTenantRead.status === 404,
      { status: crossTenantRead.status },
      { status: '401_or_404' },
      curl('GET', `/api/invoices/${firstInvoiceId}`, null, true)
    );
  }

  console.log('\n[AI]');
  const riskNoAuth = await req('POST', '/api/ai/risk-score', { customerId: TD.customers[0].id });
  record(
    'POST /api/ai/risk-score no auth -> 401',
    riskNoAuth.status === 401,
    { status: riskNoAuth.status },
    { status: 401 },
    curl('POST', '/api/ai/risk-score', { customerId: TD.customers[0].id }, false)
  );

  const riskMissing = await req('POST', '/api/ai/risk-score', {}, cookie);
  record(
    'POST /api/ai/risk-score missing customerId -> 400',
    riskMissing.status === 400,
    { status: riskMissing.status },
    { status: 400 },
    curl('POST', '/api/ai/risk-score', {}, true)
  );

  const riskAlice = await req('POST', '/api/ai/risk-score', { customerId: TD.customers[0].id }, cookie);
  record(
    'POST /api/ai/risk-score Alice -> 200',
    riskAlice.status === 200 && typeof riskAlice.json?.data?.riskScore === 'number',
    { status: riskAlice.status, riskScore: riskAlice.json?.data?.riskScore },
    { status: 200, riskScore: 'number' },
    curl('POST', '/api/ai/risk-score', { customerId: TD.customers[0].id }, true)
  );

  const emailMissing = await req('POST', '/api/ai/generate-email', { customerId: TD.customers[1].id }, cookie);
  record(
    'POST /api/ai/generate-email missing fields -> 400',
    emailMissing.status === 400,
    { status: emailMissing.status },
    { status: 400 },
    curl('POST', '/api/ai/generate-email', { customerId: TD.customers[1].id }, true)
  );

  const emailNegativeAmount = await req(
    'POST',
    '/api/ai/generate-email',
    {
      customerId: TD.customers[1].id,
      invoiceId: TD.invoices[4].id,
      customerName: 'Bob Smith',
      invoiceAmount: -10,
      dueDate: new Date().toISOString().slice(0, 10),
      daysOverdue: 10,
    },
    cookie
  );
  record(
    'POST /api/ai/generate-email negative amount -> 400',
    emailNegativeAmount.status === 400,
    { status: emailNegativeAmount.status },
    { status: 400 },
    curl(
      'POST',
      '/api/ai/generate-email',
      {
        customerId: TD.customers[1].id,
        invoiceId: TD.invoices[4].id,
        customerName: 'Bob Smith',
        invoiceAmount: -10,
        dueDate: new Date().toISOString().slice(0, 10),
        daysOverdue: 10,
      },
      true
    )
  );

  const emailFirmBody = {
    customerId: TD.customers[1].id,
    invoiceId: TD.invoices[4].id,
    customerName: 'Bob Smith',
    invoiceAmount: 2500,
    dueDate: new Date(Date.now() - 45 * 86400000).toISOString().slice(0, 10),
    daysOverdue: 45,
    riskScore: 82,
    previousReminders: 2,
    companyName: TD.companyName,
    paymentLink: 'https://pay.recoverai.test/inv-005',
  };
  const emailFirm = await req('POST', '/api/ai/generate-email', emailFirmBody, cookie);
  record(
    'POST /api/ai/generate-email valid payload -> 200',
    emailFirm.status === 200 && !!emailFirm.json?.data?.subject,
    { status: emailFirm.status, tone: emailFirm.json?.data?.tone },
    { status: 200, hasSubject: true },
    curl('POST', '/api/ai/generate-email', emailFirmBody, true)
  );

  const planMissing = await req('POST', '/api/ai/recommend-plan', { customerId: TD.customers[1].id }, cookie);
  record(
    'POST /api/ai/recommend-plan missing fields -> 400',
    planMissing.status === 400,
    { status: planMissing.status },
    { status: 400 },
    curl('POST', '/api/ai/recommend-plan', { customerId: TD.customers[1].id }, true)
  );

  const planBadAmount = await req(
    'POST',
    '/api/ai/recommend-plan',
    {
      customerId: TD.customers[1].id,
      invoiceId: TD.invoices[4].id,
      invoiceAmount: 0,
      daysOverdue: 45,
    },
    cookie
  );
  record(
    'POST /api/ai/recommend-plan zero amount -> 400',
    planBadAmount.status === 400,
    { status: planBadAmount.status },
    { status: 400 },
    curl(
      'POST',
      '/api/ai/recommend-plan',
      {
        customerId: TD.customers[1].id,
        invoiceId: TD.invoices[4].id,
        invoiceAmount: 0,
        daysOverdue: 45,
      },
      true
    )
  );

  const planBody = {
    customerId: TD.customers[1].id,
    invoiceId: TD.invoices[4].id,
    invoiceAmount: 2500,
    daysOverdue: 45,
    riskScore: 82,
    maxDurationDays: 90,
  };
  const planOk = await req('POST', '/api/ai/recommend-plan', planBody, cookie);
  record(
    'POST /api/ai/recommend-plan valid payload -> 200',
    planOk.status === 200 && !!planOk.json?.data?.recommendedPlan,
    { status: planOk.status, hasRecommendedPlan: !!planOk.json?.data?.recommendedPlan },
    { status: 200, hasRecommendedPlan: true },
    curl('POST', '/api/ai/recommend-plan', planBody, true)
  );

  console.log('\n[Policy + Feature Flags]');
  const approvalsList = await req('GET', '/api/policy/approvals?status=pending', null, cookie);
  record(
    'GET /api/policy/approvals -> 200',
    approvalsList.status === 200 && Array.isArray(approvalsList.json?.data),
    { status: approvalsList.status },
    { status: 200 },
    curl('GET', '/api/policy/approvals?status=pending', null, true)
  );

  const flagsList = await req('GET', '/api/feature-flags', null, cookie);
  record(
    'GET /api/feature-flags -> 200',
    flagsList.status === 200 && Array.isArray(flagsList.json?.data),
    { status: flagsList.status },
    { status: 200 },
    curl('GET', '/api/feature-flags', null, true)
  );

  endSummary();

  console.log('Canonical curl recap:\n');
  console.log(`# login and save cookie`);
  console.log(`curl -s -c cookies.txt -X POST "http://localhost:${PORT}/api/auth/login" -H "Content-Type: application/json" -d '{"email":"${TD.email}","password":"${TD.password}"}'`);
  console.log('');
  console.log(`# run me`);
  console.log(`curl -s -b cookies.txt "http://localhost:${PORT}/api/auth/me"`);
  console.log('');
  console.log(`# risk score (Alice)`);
  console.log(`curl -s -b cookies.txt -X POST "http://localhost:${PORT}/api/ai/risk-score" -H "Content-Type: application/json" -d '{"customerId":"${TD.customers[0].id}"}'`);
  console.log('');
  console.log(`# generate email (Bob)`);
  console.log(`curl -s -b cookies.txt -X POST "http://localhost:${PORT}/api/ai/generate-email" -H "Content-Type: application/json" -d '${JSON.stringify(emailFirmBody)}'`);
  console.log('');
  console.log(`# recommend plan (Bob)`);
  console.log(`curl -s -b cookies.txt -X POST "http://localhost:${PORT}/api/ai/recommend-plan" -H "Content-Type: application/json" -d '${JSON.stringify(planBody)}'`);
  console.log('');
  console.log(`# list invoices`);
  console.log(`curl -s -b cookies.txt "http://localhost:${PORT}/api/stripe/invoices?page=1&limit=10"`);

  if (failCount > 0) {
    process.exit(1);
  }
}

run().catch((err) => {
  console.error('[test] FATAL:', err.message);
  process.exit(1);
});

