import Anthropic from '@anthropic-ai/sdk';
import { db } from '../config/db';
import { logger } from '../config/logger';
import { config } from '../config/env';
import type { PatternResult, Severity } from './patternDetectionService';

const client = new Anthropic({ apiKey: config.anthropicApiKey });

export interface SavedBrief {
  id: string;
  briefDate: string;
  contentRaw: string;
  contentSlack: object;
  contentEmail: string;
  patternCount: number;
  severityHigh: number;
  severityMedium: number;
}

export const briefGenerationService = {
  async generateBrief(orgId: string, patterns: PatternResult[]): Promise<string> {
    if (patterns.length === 0) {
      return 'All clear today — no critical patterns detected across your team and sprint.';
    }

    const grouped = {
      HIGH: patterns.filter(p => p.severity === 'HIGH'),
      MEDIUM: patterns.filter(p => p.severity === 'MEDIUM'),
      LOW: patterns.filter(p => p.severity === 'LOW'),
    };

    const patternText = Object.entries(grouped)
      .filter(([, items]) => items.length > 0)
      .map(([sev, items]) =>
        `${sev} SEVERITY:\n${items.map(p => `- ${p.title}: ${p.description} Action: ${p.actionSuggestion}`).join('\n')}`
      )
      .join('\n\n');

    const prompt = `You are an AI Chief of Staff for a CTO. Write a concise daily engineering brief (max 150 words) summarizing these detected patterns. Be direct and actionable. Start with the biggest risks. Do not use bullet points — write in plain paragraphs.

Patterns detected:
${patternText}

Write the brief now:`;

    const message = await client.messages.create({
      model: 'claude-sonnet-4-6',
      max_tokens: 300,
      messages: [{ role: 'user', content: prompt }],
    });

    return (message.content[0] as any).text ?? '';
  },

  buildSlackBlockKit(briefText: string, patterns: PatternResult[], briefId: string): object {
    const severityEmoji: Record<Severity, string> = {
      HIGH: '🔴',
      MEDIUM: '🟡',
      LOW: '🟢',
    };

    const highCount = patterns.filter(p => p.severity === 'HIGH').length;
    const headerEmoji = highCount > 0 ? '🔴' : patterns.length > 0 ? '🟡' : '✅';
    const headerText = highCount > 0
      ? `NEEDS ATTENTION — ${highCount} high-severity issue${highCount > 1 ? 's' : ''}`
      : patterns.length > 0 ? 'WATCH — Items need monitoring' : 'HEALTHY — All clear';

    const blocks: object[] = [
      {
        type: 'header',
        text: { type: 'plain_text', text: `${headerEmoji} Engineering Brief — ${new Date().toLocaleDateString('en-US', { weekday: 'long', month: 'long', day: 'numeric' })}` },
      },
      {
        type: 'section',
        text: { type: 'mrkdwn', text: `*${headerText}*` },
      },
      {
        type: 'section',
        text: { type: 'mrkdwn', text: briefText },
      },
      { type: 'divider' },
    ];

    // Add action items (max 10 to stay within Slack limits)
    for (const pattern of patterns.slice(0, 10)) {
      blocks.push({
        type: 'section',
        text: {
          type: 'mrkdwn',
          text: `${severityEmoji[pattern.severity]} *${pattern.title}*\n${pattern.description}\n_${pattern.actionSuggestion}_`,
        },
        accessory: {
          type: 'overflow',
          action_id: `brief_action:${briefId}`,
          options: [
            { text: { type: 'plain_text', text: '✅ Acknowledge' }, value: `ack:${pattern.prId ?? pattern.ticketId ?? 'none'}` },
            { text: { type: 'plain_text', text: '🚫 Dismiss' }, value: `dismiss:${pattern.prId ?? pattern.ticketId ?? 'none'}` },
            { text: { type: 'plain_text', text: '⏰ Snooze 1 day' }, value: `snooze:${pattern.prId ?? pattern.ticketId ?? 'none'}` },
          ],
        },
      });
    }

    blocks.push({
      type: 'context',
      elements: [
        { type: 'mrkdwn', text: `_Generated by EngineeringOS · ${patterns.length} pattern${patterns.length !== 1 ? 's' : ''} detected_` },
      ],
    });

    return { blocks };
  },

  buildEmailHTML(briefText: string, patterns: PatternResult[]): string {
    const severityColor: Record<Severity, string> = {
      HIGH: '#dc2626',
      MEDIUM: '#d97706',
      LOW: '#16a34a',
    };
    const severityEmoji: Record<Severity, string> = { HIGH: '🔴', MEDIUM: '🟡', LOW: '🟢' };

    const highCount = patterns.filter(p => p.severity === 'HIGH').length;
    const headerColor = highCount > 0 ? '#dc2626' : patterns.length > 0 ? '#d97706' : '#16a34a';
    const headerText = highCount > 0 ? 'NEEDS ATTENTION' : patterns.length > 0 ? 'WATCH' : 'HEALTHY';

    const patternRows = patterns.map(p => `
      <tr>
        <td style="padding:12px;border-bottom:1px solid #f3f4f6;">
          <div style="font-weight:600;color:${severityColor[p.severity]};">${severityEmoji[p.severity]} ${p.title}</div>
          <div style="color:#374151;margin-top:4px;">${p.description}</div>
          <div style="color:#6b7280;font-style:italic;margin-top:4px;">${p.actionSuggestion}</div>
        </td>
      </tr>`).join('');

    return `<!DOCTYPE html>
<html>
<head><meta charset="utf-8"><title>Engineering Brief</title></head>
<body style="font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;background:#f9fafb;margin:0;padding:20px;">
  <div style="max-width:600px;margin:0 auto;background:#fff;border-radius:8px;overflow:hidden;box-shadow:0 1px 3px rgba(0,0,0,0.1);">
    <div style="background:${headerColor};padding:20px 24px;">
      <div style="color:rgba(255,255,255,0.8);font-size:12px;text-transform:uppercase;letter-spacing:0.05em;">Engineering Brief</div>
      <div style="color:#fff;font-size:20px;font-weight:700;margin-top:4px;">${headerText}</div>
      <div style="color:rgba(255,255,255,0.8);font-size:13px;margin-top:4px;">${new Date().toLocaleDateString('en-US', { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' })}</div>
    </div>
    <div style="padding:24px;">
      <p style="color:#111827;line-height:1.6;margin:0 0 20px;">${briefText}</p>
      ${patterns.length > 0 ? `
      <h2 style="font-size:14px;font-weight:600;color:#374151;margin:0 0 12px;text-transform:uppercase;letter-spacing:0.05em;">Action Items</h2>
      <table style="width:100%;border-collapse:collapse;border:1px solid #e5e7eb;border-radius:6px;overflow:hidden;">
        ${patternRows}
      </table>` : ''}
    </div>
    <div style="background:#f9fafb;padding:16px 24px;text-align:center;">
      <p style="color:#9ca3af;font-size:12px;margin:0;">Generated by EngineeringOS · ${patterns.length} pattern${patterns.length !== 1 ? 's' : ''} detected</p>
    </div>
  </div>
</body>
</html>`;
  },

  async saveBrief(orgId: string, contentRaw: string, patterns: PatternResult[]): Promise<SavedBrief> {
    const today = new Date().toISOString().split('T')[0];
    const highCount = patterns.filter(p => p.severity === 'HIGH').length;
    const mediumCount = patterns.filter(p => p.severity === 'MEDIUM').length;

    // Save brief record first (get ID for Block Kit)
    const { rows } = await db.query(
      `INSERT INTO daily_briefs
         (org_id, brief_date, content_raw, pattern_count, severity_high, severity_medium)
       VALUES ($1, $2, $3, $4, $5, $6)
       ON CONFLICT (org_id, brief_date) DO UPDATE SET
         content_raw = $3, pattern_count = $4, severity_high = $5, severity_medium = $6,
         sent_at = NULL
       RETURNING id, brief_date`,
      [orgId, today, contentRaw, patterns.length, highCount, mediumCount]
    );
    const briefId: string = rows[0].id;

    // Build formatted content now that we have an ID
    const contentSlack = briefGenerationService.buildSlackBlockKit(contentRaw, patterns, briefId);
    const contentEmail = briefGenerationService.buildEmailHTML(contentRaw, patterns);

    await db.query(
      `UPDATE daily_briefs SET content_slack = $2, content_email = $3 WHERE id = $1`,
      [briefId, contentSlack, contentEmail]
    );

    // Save brief_items
    for (const pattern of patterns) {
      await db.query(
        `INSERT INTO brief_items
           (brief_id, org_id, pattern_type, severity, title, description, action_suggestion,
            engineer_github_id, pr_id, ticket_id)
         VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10)`,
        [briefId, orgId, pattern.patternType, pattern.severity, pattern.title,
         pattern.description, pattern.actionSuggestion, pattern.engineerGithubId ?? null,
         pattern.prId ?? null, pattern.ticketId ?? null]
      );
    }

    logger.info({ orgId, briefId, patternCount: patterns.length }, '[Brief] Saved brief');

    return {
      id: briefId,
      briefDate: today,
      contentRaw,
      contentSlack,
      contentEmail,
      patternCount: patterns.length,
      severityHigh: highCount,
      severityMedium: mediumCount,
    };
  },
};
